language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - libglew-dev
      - xorg-dev
            
compiler:
  - gcc
  - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" COMPILER="gcc" GMAKE_FOLDER="gmake-linux"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7" COMPILER="clang" GMAKE_FOLDER="gmake-linux-clang"; fi

before_script:
  - git clone https://github.com/glfw/glfw
  - mkdir glfw/build
  - cd glfw/build
  - cmake .. -DBUILD_SHARED_LIBS=ON
  - make VERBOSE=1
  - sudo make install
  - cd ../..
  
script:
  - bin/genie --gcc=linux-$CC gmake
  - cd build/projects/$GMAKE_FOLDER
  - make config=debug64 -j8

os:
  - linux